name: Kontrol
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  
jobs:
  BirlesikGuncelleme:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4.2.2
        
      - name: Python 3.11.8 YÃ¼kle
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.11.8
          
      - name: Gereksinimleri Kur
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel Kekik httpx parsel requests cloudscraper beautifulsoup4
          
      - name: inn.py Ã‡alÄ±ÅŸtÄ±r
        continue-on-error: true
        run: python inn.py
      - name: oki.py Ã‡alÄ±ÅŸtÄ±r
        continue-on-error: true
        run: python oki.py  
      - name: an.py Ã‡alÄ±ÅŸtÄ±r
        continue-on-error: true
        run: python an.py
      - name: selcuk.py Ã‡alÄ±ÅŸtÄ±r
        continue-on-error: true
        run: python selcuk.py
      - name: r.py Ã‡alÄ±ÅŸtÄ±r
        continue-on-error: true
        run: python r.py
      - name: r2.py Ã‡alÄ±ÅŸtÄ±r
        continue-on-error: true
        run: python r2.py
      - name: ftb.py Ã‡alÄ±ÅŸtÄ±r
        continue-on-error: true
        run: python ftb.py
      - name: kbl.py Ã‡alÄ±ÅŸtÄ±r
        continue-on-error: true
        run: python kbl.py        
      - name: rnl.py Ã‡alÄ±ÅŸtÄ±r
        continue-on-error: true
        run: python rnl.py        
      - name: fll.py Ã‡alÄ±ÅŸtÄ±r
        continue-on-error: true
        run: python fll.py 
      - name: jungle.py Ã‡alÄ±ÅŸtÄ±r
        continue-on-error: true
        run: python jungle.py 
      - name: DeÄŸiÅŸiklik KontrolÃ¼
        id: degisiklik_kontrol
        run: |
          git diff --quiet . || echo "degisiklik=true" >> $GITHUB_OUTPUT
          
      - name: DeÄŸiÅŸiklikleri Commit Et
        if: steps.degisiklik_kontrol.outputs.degisiklik == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ğŸ”„ Kanallar gÃ¼ncellendi" -m "ğŸ“º Domain kontrolÃ¼ ve M3U gÃ¼ncellemeleri tamamlandÄ±" -m "ğŸ•’ Otomatik iÅŸlem - $GITHUB_SHA"
          git push

